config-version: 2

name: 'xplat_foundation'
version: "3.0.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  xplat_foundation:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  xplat_foundation:
    marts:
      +materialized: table
      +access: public 
      +file_format: iceberg 
      +catalog: coalesce_cross_platform_mesh_iceberg 
      intermediate: 
        +materialized: table
        +file_format: delta
      standard_tables:
        +materialized: table
        +file_format: delta

flags:
  require_generic_test_arguments_property: true
  use_materialization_v2: true
